# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
      
jobs:
  build:
    outputs:
      version: ${{ steps.vsix_version.outputs.version-number }}
    name: Build 
    runs-on: windows-2022
    env:
      Configuration: Release
      DeployExtension: False
      VsixManifestPath: Functionator\source.extension.vsixmanifest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'
    - name: Increment VSIX version
      id: vsix_version
      uses: timheuer/vsix-version-stamp@v1
      with:
        manifest-file: ${{ env.VsixManifestPath }}
    - name: Build
      run: msbuild /v:m -restore /p:OutDir=\_built
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.15.2 -DirectDownload -OutputDirectory .

    - name: Test
      run: ./NUnit.ConsoleRunner.3.15.2/tools/nunit3-console.exe FunctionatorTests\bin\Debug\FunctionatorTests.dll
